name: Client CI
    
on:
  push:
    branches:
      - master
    paths:
      - "Client/**"
      - ".github/workflows/client.yml"
  pull_request:
    branches:
      - master
    paths:
      - "Client/**"
      - ".github/workflows/client.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: gradle

    - name: Build with Gradle
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |-
        cd Client
        chmod +x gradlew
        ./gradlew build
